### ISSUE TITLE
First Overall Winner Not Correctly Represented in Filtered Results

### ISSUE THREAD

**Issue by PhillyWebGuy** [RunSignUp-Team/OpenSource#3]
Here we have the 1st place overall winner. Note that he is 46 years old. Note that his age group is "M Overall"

![image](https://github.com/RunSignUp-Team/OpenSource/assets/449963/44a7f9d8-3b93-43dc-8943-55fc7b478d5d)

Now filter for Males 40-49. Since the 1st overall winner doesn't get set to the Male 40-49 category, he won't show up when you filter by that age range:

![image](https://github.com/RunSignUp-Team/OpenSource/assets/449963/6fa30990-a3bf-43c2-9367-86e917af3be1)

**Comment by ssigwart** [comment]
This is dependent on how the race uploads division results and if they allow double dipping.
